# Generated by Django 3.2.4 on 2021-06-16 02:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('vin', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=6)),
                ('año_fabricacion', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)])),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('marca', models.TextField(max_length=30)),
                ('modelo', models.TextField(max_length=30)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
